"""
Django settings for sgdsep project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&=u&#tb!=y9rl*9g-xmg!8)ir9qtnu^o632401jha)@c*wbu^t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sgdsistem',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sgdsep.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sgdsep.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'nominas',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',  # Cambia si tu base de datos no está en el localhost
        'PORT': '3306',       # Cambia si usas un puerto diferente
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


JAZZMIN_SETTINGS = {
    "site_title": "Administración de Nóminas SEP",  # Título en la pestaña del navegador
    "site_header": "Administración de Nóminas SEP",  # Título principal en la barra superior
    "site_brand": "Nóminas SEP",  # Nombre de la aplicación
    "welcome_sign": "Bienvenido al panel de administración de Nóminas SEP",  # Mensaje de bienvenida
    "show_sidebar": True,  # Mostrar barra lateral
    "show_navigation": True,  # Mostrar navegación
    "order_with_respect_to": ["auth", "contenttypes"],  # Orden de los módulos en el admin
    # Personalización de temas (si deseas modificar colores, iconos, etc.)
    "icons": {
        "auth.user": "fas fa-users",  # Icono para el modelo de usuario
        "auth.group": "fas fa-users-cog",  # Icono para el grupo de usuarios
        # Agrega más iconos si lo deseas
    },
}

JAZZMIN_SETTINGS.update({
    "navigation_expanded": True,  # Expande la barra lateral por defecto
    "navigation": [
        {"name": "Nómina", "url": "/admin/nómina", "icon": "fas fa-dollar-sign"},
        {"name": "Empleados", "url": "/admin/empleados", "icon": "fas fa-user-friends"},
        {"name": "Configuración", "url": "/admin/config", "icon": "fas fa-cogs"},
    ],
})


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-la'

TIME_ZONE = 'America/Mexico_City'  # Ajusta esto a tu zona horaria
USE_TZ = True  # Asegúrate de que el uso de zona horaria esté habilitado




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = '/static/'
LOGIN_URL = '/signin'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'sgdsistem.CustomUser'
