# Generated by Django 5.1.3 on 2024-12-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdsistem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plazasdata',
            name='cve_plaza',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='plazasdata',
            name='docto_pla',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='plazasdata',
            name='nivel_pto',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
