from django import forms
from django.forms import ClearableFileInput, ModelForm

from sgdsistem.models import Inmuebles_data

      
class InmueblesForm(forms.ModelForm):
    class Meta:
        model = Inmuebles_data
        fields = [
                  'CV_CCT', 'assigned_to', 'estado', 'deadline', 'prioridad',
                  'creado', 'datecompleted', 'user', 'fotografia_de_la_ubicacion',
                  'C_NOMBRE', 'CV_TIPO', 'C_TIPO', 'CV_ADMINISTRATIVA', 'C_ADMINISTRATIVA',
                  'CV_ESTATUS', 'C_ESTATUS', 'F_FUNDACION', 'ALTA_SISTEMA', 'CAMBIO', 'CLAUSURA',
                  'REAPERTURA', 'REAPERTURA_CON_CAMBIO', 'INMUEBLE_CV_INMUEBLE', 'INMUEBLE_C_VIALIDAD_PRINCIPAL',
                  'INMUEBLE_C_VIALIDAD_DERECHA', 'INMUEBLE_C_VIALIDAD_IZQUIERDA', 'INMUEBLE_C_VIALIDAD_POSTERIOR',
                  'INMUEBLE_N_EXTNUM', 'INMUEBLE_C_EXTALF', 'INMUEBLE_N_INTNUM', 'INMUEBLE_C_INTALF',
                  'INMUEBLE_CV_ENT', 'INMUEBLE_C_NOM_ENT', 'INMUEBLE_CV_MUN', 'INMUEBLE_C_NOM_MUN',
                  'Zona_Economica', 'INMUEBLE_CV_LOC', 'INMUEBLE_C_NOM_LOC', 'INMUEBLE_CV_AMBITO',
                  'INMUEBLE_C_NOM_AMBITO', 'INMUEBLE_CV_ASEN', 'INMUEBLE_C_NOM_ASEN', 'INMUEBLE_CV_TIPO_ASEN',
                  'INMUEBLE_C_TIPO_ASEN', 'INMUEBLE_CV_CODIGO_POSTAL', 'INMUEBLE_C_DESC_UBICACION',
                  'INMUEBLE_LATITUD', 'INMUEBLE_LONGITUD', 'SOSTENIMIENTO_CV_CONTROL', 'SOSTENIMIENTO_C_CONTROL',
                  'SOSTENIMIENTO_CV_SUBCONTROL', 'SOSTENIMIENTO_C_SUBCONTROL', 'SOSTENIMIENTO_CV_DEPENDENCIAN1',
                  'SOSTENIMIENTO_C_DEPENDENCIAN1', 'SOSTENIMIENTO_CV_DEPENDENCIAN2', 'SOSTENIMIENTO_C_DEPENDENCIAN2',
                  'SOSTENIMIENTO_CV_DEPENDENCIAN3', 'SOSTENIMIENTO_C_DEPENDENCIAN3', 'SOSTENIMIENTO_CV_DEPENDENCIAN4',
                   'SOSTENIMIENTO_C_DEPENDENCIAN4', 'DEPOPERATIVA_CV_DEPENDENCIAN5', 'DEPOPERATIVA_C_DEPENDENCIAN5',
                   'CONTACTO_CV_CARGO', 'CONTACTO_C_CARGO', 'CONTACTO_CV_TIPODIRECTOR', 'CONTACTO_C_TIPODIRECTOR',
                   'CONTACTO_C_ASOCIACION', 'CONTACTO_C_CURP', 'CONTACTO_C_RFC', 'CONTACTO_C_NOMBRE', 
                   'CONTACTO_C_APELLIDO1', 'CONTACTO_C_APELLIDO2', 'CONTACTO_C_TELEFONO', 'CONTACTO_C_CELULAR',
                   'CONTACTO_C_EMAIL', 'CONTACTO_C_EXTENSION', 'CONTACTO_C_PWEB', 'SUPERVISION_CV_CCT', 'JEFSEC_CV_CCT',
                   'SERREG_CV_CCT', 'INSTITUCION_PLANTEL', 'C_TURNO_1', 'C_TURNO_2', 'C_TURNO_3',
                   'TIPONIVELSUB_CV_SERVICION1', 'TIPONIVELSUB_C_SERVICION1', 'TIPONIVELSUB_CV_SERVICION2',
                   'TIPONIVELSUB_C_SERVICION2', 'TIPONIVELSUB_CV_SERVICION3', 'TIPONIVELSUB_C_SERVICION3',
                   'C_SERVICIO_CAM', 'CARACTERISTCA_CV_CARACTERIZAN1', 'CARACTERISTCA_C_CARACTERIZAN1',
                   'CARACTERISTCA_CV_CARACTERIZAN2', 'CARACTERISTCA_C_CARACTERIZAN2'
                  ]


class CSVUploadForm(forms.Form):
    csv_file = forms.FileField()